spring:
  # 数据源
  datasource:
    dynamic:
      primary: master
      datasource:
        master:
          driver-class-name: com.mysql.cj.jdbc.Driver
          url: jdbc:mysql://localhost:60006/tyrande?usrSSL=true&useUnicode=true&characterEncoding=utf-8&serverTimezone=Asia/Shanghai&nullCatalogMeansCurrent=true
          username: root
          password: 123456
        flow:
          driver-class-name: com.mysql.cj.jdbc.Driver
          url: jdbc:mysql://localhost:60006/tyrande_flow?usrSSL=true&useUnicode=true&characterEncoding=utf-8&serverTimezone=Asia/Shanghai&nullCatalogMeansCurrent=true
          username: root
          password: 123456
        job:
          driver-class-name: com.mysql.cj.jdbc.Driver
          url: jdbc:mysql://localhost:60006/tyrande_job?usrSSL=true&useUnicode=true&characterEncoding=utf-8&serverTimezone=Asia/Shanghai&nullCatalogMeansCurrent=true
          username: root
          password: 123456
  # redis
  redis:
    host: localhost
    port: 60007
    password: redis123
    timeout: 3600
    jedis:
      pool:
        max-active: 8
        max-idle: 8
        max-wait: -1ms
        min-idle: 0

# mybatis plus 配置
mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
    map-underscore-to-camel-case: true
  mapper-locations: classpath*:/mappers/**/*.xml, classpath*:/mappers/*.xml

# 调度任务
xxl:
  job:
    admin:
      address: http://localhost:60008/tyrande-job
    executor:
      appname: tyrande-job

# 工作流
flowable:
  data-source: flow
  database-schema: tyrande_flow
  database-schema-update: false
  deployment-name: tyrande-flow
  async-executor-activate: false
  async-history-executor-activate: false