server:
  port: 7703
  servlet:
    context-path: /tyrande

spring:
  application:
    name: tyrande
  profiles:
    active: dev
    include: common,generator,basemq
  cache:
    type: caffeine
  servlet:
    multipart:
      max-file-size: 5MB
      max-request-size: 20MB