spring:
  # 炫彩日志
  output:
    ansi:
      enabled: detect
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/tyrande-0?usrSSL=true&useUnicode=true&characterEncoding=utf-8&serverTimezone=Asia/Shanghai
    username: root
    password: 123456

# mybatis plus 配置
mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
    map-underscore-to-camel-case: true
  mapper-locations: classpath:/mappers/**/*.xml

# 日志
logging:
  file:
    path: d://tyrande_log
    name: tyrande.log
  level:
    org.tyrande.*.dao: debug

