spring:
  # 炫彩日志
  output:
    ansi:
      enabled: detect
  # 数据源
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:60006/tyrande-0?usrSSL=true&useUnicode=true&characterEncoding=utf-8&serverTimezone=Asia/Shanghai
    username: root
    password: 123456
  # redis
  redis:
    host: localhost
    port: 60007
    password: redis123
    timeout: 3600
    jedis:
      pool:
        max-active: 8
        max-idle: 8
        max-wait: -1ms
        min-idle: 0

# mybatis plus 配置
mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
    map-underscore-to-camel-case: true
  mapper-locations: classpath*:/mappers/**/*.xml, classpath*:/mappers/*.xml

# 调度任务
xxl:
  job:
    admin:
      addresses: http://localhost:60008/tyrande-job
    executor:
      appname: tyrande-job

